apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
data:
  AWS_S3_URL: Cg==
  AWS_SECRET_ACCESS_KEY: bnBsQi8yaXpOQ2l6R2EyM3c3TzgxZkJzL1RabFVkWjZYOEJ6MUVVdAo=
  AWS_ACCESS_KEY_ID: 
