# ClickHouse using default storage class. 
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "demo"
spec:
  configuration:
    clusters:
      - name: "cl"
        layout:
          replicasCount: 1
          shardsCount: 2
        templates:
          volumeClaimTemplate: storage
          podTemplate: replica
    zookeeper:
        nodes:
        - host: zookeeper.zoo1ns
          port: 2181
  templates:
    podTemplates:
      - name: replica
        spec:
          containers:
          - name: clickhouse
            image: altinity/clickhouse-server:23.3.13.7.altinitystable
    volumeClaimTemplates:
      - name: storage
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
