apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "secure"
spec:
  configuration:
    clusters:
      - name: "ch"
        layout:
          replicasCount: 1
          shardsCount: 1
        templates:
          volumeClaimTemplate: storage
          podTemplate: replica
    users:
      root/networks/ip: "::/0"
      root/k8s_secret_password_sha256_hex: db-passwords/password_sha256_hex
      root/profile: "default"
      root/access_management: 1
    files:
      config.d/s3.xml: |
        <clickhouse>
          <s3>
            <playground>
              <endpoint>https://rhodges-us-west-2-playground-1.s3.amazonaws.com/k8s/security/</endpoint>
              <region>us-west-2</region>
              <use_environment_credentials>true</use_environment_credentials> 
            </playground>
          </s3>
        </clickhouse>
  templates:
    podTemplates:
      - name: replica
        spec:
          containers:
          - name: clickhouse
            image: altinity/clickhouse-server:23.3.8.22.altinitystable
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: AWS_SECRET_ACCESS_KEY
    volumeClaimTemplates:
      - name: storage
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
