# Example of user passwords from Secrets for operator versions *BEFORE* 0.23.0.
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "secure"
spec:
  # Update taskId to pick up changes to secret. 
  taskID: "1"
  configuration:
    clusters:
      - name: "ch"
        layout:
          replicasCount: 1
          shardsCount: 1
        templates:
          volumeClaimTemplate: storage
          podTemplate: replica
    users:
      default/k8s_secret_password_sha256_hex: db-passwords/default_password_sha256
      root/networks/ip: "::/0"
      root/k8s_secret_password_sha256_hex: db-passwords/root_password_sha256
      root/profile: "default"
      root/access_management: 1
  templates:
    podTemplates:
      - name: replica
        spec:
          containers:
          - name: clickhouse
            image: altinity/clickhouse-server:23.8.8.21.altinitystable
    volumeClaimTemplates:
      - name: storage
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
