---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/<role-name>
  name: s3-iam
---

apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "secure"
spec:
  configuration:
    clusters:
      - name: "ch"
        layout:
          replicasCount: 1
          shardsCount: 1
        templates:
          volumeClaimTemplate: storage
          podTemplate: replica
    users:
      default/password_sha256_hex: 53336a676c64c1396553b2b7c92f38126768827c93b64d9142069c10eda7a721
      root/networks/ip: "::/0"
      root/password_sha256_hex: 53336a676c64c1396553b2b7c92f38126768827c93b64d9142069c10eda7a721
      root/profile: "default"
      root/access_management: 1
    files:
      config.d/s3.xml: |
        <clickhouse>
          <s3>
            <playground>
              <endpoint>https://rhodges-us-west-2-playground-1.s3.amazonaws.com/k8s/security/</endpoint>
              <region>us-west-2</region>
              <use_environment_credentials>true</use_environment_credentials> 
            </playground>
          </s3>
        </clickhouse>
  templates:
    podTemplates:
      - name: replica
spec:
  serviceAccountName: s3-iam
  containers:
  - name: clickhouse
    image: altinity/clickhouse-server:23.8.8.21.altinitystable

    volumeClaimTemplates:
      - name: storage
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

