apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "secure"
spec:
  taskID: "1"
  configuration:
    clusters:
      - name: "ch"
        layout:
          replicasCount: 1
          shardsCount: 1
        templates:
          volumeClaimTemplate: storage
          podTemplate: replica
    users:
      default/password_sha256_hex: 53336a676c64c1396553b2b7c92f38126768827c93b64d9142069c10eda7a721
      root/networks/ip: "::/0"
      root/password_sha256_hex: 53336a676c64c1396553b2b7c92f38126768827c93b64d9142069c10eda7a721
      root/profile: "default"
      root/access_management: 1
    files:
      config.d/s3.xml: |
        <clickhouse>
          <s3>
            <playground>
              <endpoint from_env="MY_AWS_S3_ENDPOINT"/>
              <secret_access_key from_env="MY_AWS_SECRET_ACCESS_KEY"/>
              <access_key_id from_env="MY_AWS_ACCESS_KEY_ID"/>
              <region>us-west-2</region>
              <use_environment_credentials>false</use_environment_credentials>
            </playground>
          </s3>
        </clickhouse>
  templates:
    podTemplates:
      - name: replica
        spec:
          containers:
          - name: clickhouse
            image: altinity/clickhouse-server:23.8.8.21.altinitystable
            env:
            - name: MY_AWS_S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: AWS_S3_ENDPOINT
            - name: MY_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: MY_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: AWS_SECRET_ACCESS_KEY
    volumeClaimTemplates:
      - name: storage
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
