apiVersion: v1
kind: Secret
metadata:
  name: server-crt
type: Opaque
stringData:
  ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIDDTCCAfWgAwIBAgIUYw8yEunsC3CX/RxSTJd1/bVoLvswDQYJKoZIhvcNAQEL
    BQAwFjEUMBIGA1UEAwwLRm9ydHJlc3MgQ0EwHhcNMjMwOTI3MDQyNTEyWhcNMzMw
    OTI0MDQyNTEyWjAWMRQwEgYDVQQDDAtGb3J0cmVzcyBDQTCCASIwDQYJKoZIhvcN
    AQEBBQADggEPADCCAQoCggEBANm0xUfSjtiH9RNtQki9aHsaWxZ/USiStfGs9rh1
    n/7bYKD6unTiNDfp73Y2kzYMBOIfu7fcD1vdqqv4bbHhYqHPrlNTyEj2kBJVWUUR
    OwprC8uM3MHVVXYVoJ3mxrLB5xgIxnWFzA+23BdnCtVoFqf7KDtXOg/Qptl/nJtS
    K+MlOtGYQUbd+N5882j2tMbw4R3N4AhQxAgp4+bQ+YixWEwGacRoIrxDFGqPtGae
    j4nkM2o1o2YIQXZ3MBDQ86Tulv2JVnXbVe4yUwC/NXblle1N4A4MEcK0j23vo3qp
    f9zWXLpA7zFQVVu8YgJJE0ofJcfqAqmxEvoAvBxsUw9qktsCAwEAAaNTMFEwHQYD
    VR0OBBYEFBW1lBEP+lDCiyUXCxlFBaaO4N8kMB8GA1UdIwQYMBaAFBW1lBEP+lDC
    iyUXCxlFBaaO4N8kMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
    AEF3FvqfbyxKDxF2ltn/vi9Y1UUirrJd6eRuDBx11n7ZElU6P4HD/3U5Ku4h0oFh
    IRnSi/DD3moC1D/bNFKlniT6g9TyySbBdjv2+XgOBHnXMJ16qWLyFZSFiSJUoCgo
    5F2PepuMelTJM/8FhPF3bqcq3RlemOvs/x5FYH9jJosBmpdyyD81TFB/bGlvUX4/
    r1nrAFAGG04h0AXfDdFGzCm8UJqAC7viU2hgAA0rAWncHUdD3Aj6mwOFiS22X8Ez
    fea9zAJWOqbT/7DzHAiqEczoe4TuZmWDGMiOVmc4cPM36UiG3/obuoyEuPC0zsp+
    l3RNRDnrNMB2Pypl/v9vKzU=
    -----END CERTIFICATE-----
  server.crt: |-
    -----BEGIN CERTIFICATE-----
    MIICsDCCAZgCFD9KsduOqdgCSB6ftWw+w4e5j+shMA0GCSqGSIb3DQEBCwUAMBYx
    FDASBgNVBAMMC0ZvcnRyZXNzIENBMB4XDTIzMDkyNzA0MjUxMloXDTI0MDkyNjA0
    MjUxMlowEzERMA8GA1UEAwwIZm9ydHJlc3MwggEiMA0GCSqGSIb3DQEBAQUAA4IB
    DwAwggEKAoIBAQC3opGOkN6gBDMN/jYScAO6V7hndRYMTmEA36M3dX42Ts+MR6vK
    ubTPLV03cK4mtmBDMCkZjVbyACBW0F/D5qlxwjhUzrDiDoXqhZg/0oUpgwOXkD/n
    lY558vdXmAzqnb+4eAYFutoLJMAxDAvteJxfEIdoynhEmPRykFyl2qSMkbh+0pJU
    qyzW+3BMOtd+LAD6xtd9AVSbP5/flxoMItmPbJDJEMyIlxs/3bzdh67nZ3nfUmsF
    jcvkIw5gibJkPlVzzudpa1uPNkNIw7QcB/vYXM+2YIa/1gBbJz3UcbnkgTZMiOoY
    zR2p/W3B+b/i9oAZtLtYZo6S5ENwA8GGBOybAgMBAAEwDQYJKoZIhvcNAQELBQAD
    ggEBAM2HQlXT8fTNgXZvrdGkM3UXEV99YFD5ZBhExuvTCE2T1lRh/IZhKTQi2MaS
    +lA/bMUTWhAVq+j7mo6RyAaxyANse4Pk8x+WGPs49zI8MCEPyTQdN5VVZXdo1N+Y
    4jdUxSgLyj4yZ9TPbjZ8SCWokFYxp+gS+1oR225PY5T+LthbSqDn8ttZB7gH5nMC
    T7OfqYYK+THcSLGnH27RG1apGDHAbsRWoRuXQCa8exX8sZeZq2W1NsFGp2PaFXp/
    dzkDr5jdkM023pn4Z23pwdiKnjJ48GlLRQ25si0nvq65N/lz3RVBaWDfw/xcBkyj
    mt8IlJLU4vdpgY/6vyyFVoNldUk=
    -----END CERTIFICATE-----
  server.key: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC3opGOkN6gBDMN
    /jYScAO6V7hndRYMTmEA36M3dX42Ts+MR6vKubTPLV03cK4mtmBDMCkZjVbyACBW
    0F/D5qlxwjhUzrDiDoXqhZg/0oUpgwOXkD/nlY558vdXmAzqnb+4eAYFutoLJMAx
    DAvteJxfEIdoynhEmPRykFyl2qSMkbh+0pJUqyzW+3BMOtd+LAD6xtd9AVSbP5/f
    lxoMItmPbJDJEMyIlxs/3bzdh67nZ3nfUmsFjcvkIw5gibJkPlVzzudpa1uPNkNI
    w7QcB/vYXM+2YIa/1gBbJz3UcbnkgTZMiOoYzR2p/W3B+b/i9oAZtLtYZo6S5ENw
    A8GGBOybAgMBAAECggEABYkNeS4tv8YQoenZSGn++sV9JgU2Am30Z5nWKixM/ycW
    A4T/jS9W323fIvYvEbSqpyvS+VW02rudPfCvClEwJ2Ey4H+QfmfwqnaXdckLQYqU
    96MeAgWUk2F7CjVnokTaDB32FIMi4nYbov7ZdzGNCSKO6l48DNlNeQyX9lnmXuRS
    cPHn31OcfkvZyxqHtRzczPDTl0qBMxVVcv9MkiLV/2U4avbdwrhkG94hpDIzW7UU
    0qoBdFXsfz8EUczTngl9c6Fu4KKaIr8saIApZqd3jmAB0sNaTFCsTrxVLjTsGSHk
    /Bl7ihdUzgcewFRIgm0eODs6yxDGGYiRdKSQEcQl7QKBgQD0LEylNcMsG0I7e0Ei
    jq5msOzRKnbBQKTLdwPPMgAxeUFNqsDCMgwIQ3TVJQpmYM1WRnoctvCknsYmkX1m
    vimdmOEx9NIp0VQtEntucqxMe8+uQ3d92Os9zYvg7nRiNHSO6gAOcqUEdUTLVJD+
    2I6BXnSKfMvgamNbBYBXIwOXvQKBgQDAh5vqPVyGesFsakzckh0i1ZhicaFBLx+3
    qXdsGYQGM6/KH+VLxLzbnlzqyc9OHCdirKEWFjG/QUdzRMJgZoEemjbstzWBpuf2
    gV6CVRQgH4HlSQfeYCZas10KzLTtrZaVodehEON+0h1q10cVDQvW5x9m7B4wrYDY
    MLcHVtxPNwKBgGHlsQU8PPheJXv7uu3EDyCVJx3lzJ9G78uz+A8GmRU87HXbVFWI
    A1L82MbshvLtNOa2cxc4MduO3Rtxkbmz3LOXLBL/eZPSndFEa8CosXQo3+eanToT
    0p2A3+hbMsZ9CY6TO1qPlKHo8qAjU88ZvGkaGde8mXFstlE0L3TAURxxAoGAYwBY
    qGbNQUm2VK2EwJdR7CuxpE2SAhbdVHAMPMYSIa5KYsFsAz4zbytL1F/Z/ex0REVI
    wDbBdft3ZkqhOTj8hGQAglDjbrwI47U6iAJ/ytTo0qJvLWZ70oARBBCnqOBuYptK
    akRo9znMbrgskSKYR/WpLB+Wlqlha8oBFAESYJkCgYAcpctOkXRVxKsDXoxadP39
    HAIB+RQD0+BRyODJrSK/KrD55KaluaZz8FaDFFSLPA9Gwt/YYJmelPIR90SQxCxZ
    IZ4EyjUXSN/CYVidUFDJYG6tOQfsHGm4e0nb4jPpN94sPaYxWdIjjxeRv6XDt/NG
    iC+MAzRkF994/d528Br3Yw==
    -----END PRIVATE KEY-----
