# ClickHouse using default storage class. 
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "{{ .Values.clickhouse.name }}"
  labels:
    application_group: "{{ .Values.all.metadata.labels.application_group }}"
spec:
  configuration:
    clusters:
      - name: "{{ .Values.clickhouse.cluster }}"
        layout:
          replicasCount: {{ .Values.clickhouse.replicasCount }}
          shardsCount: {{ .Values.clickhouse.shardsCount }}
        templates:
          volumeClaimTemplate: storage
          podTemplate: replica
    zookeeper:
        nodes:
        - host: "{{ .Values.keeper.name }}"
          port: 2181
  templates:
    podTemplates:
      - name: replica
        spec:
          containers:
          - name: clickhouse
            image: "{{ .Values.clickhouse.image }}"
    volumeClaimTemplates:
      - name: storage
        reclaimPolicy: Retain
        metadata:
          labels:
            application_group: "{{ .Values.all.metadata.labels.application_group }}"
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "{{ .Values.clickhouse.storage }}"
