apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-{{ .Values.clickhouse.name }}
type: Opaque
stringData:
  login: "{{ .Values.clickhouse.user.login }}"
  password: "{{ .Values.clickhouse.user.password }}"
