{
 "title": "US Airline Comparative Ontime Statistics",
 "description": "ClickHouse dashhboard for sample data from the Airline Carrier On-Time dataset from US Bureau of Transportation Statistics.  See https://clickhouse.yandex/docs/en/getting_started/example_datasets/ontime/ for download instructions. ",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "carrier",
    "label": "Airline Carrier",
    "query": "select distinct Carrier from airline.ontime order by Carrier"
   }
  ]
 },
 "panels": [
  {
   "title": "Selected Carrier Name",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT '$carrier'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of Flights By All Carriers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "airline",
     "dateColDataType": "FlightDate",
     "dateTimeColDataType": "toDateTime(FlightDate)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, Carrier, count() Flights\n  FROM $table \n WHERE $timeFilter \n GROUP BY t, Carrier ORDER BY t, Carrier ",
     "round": "0s",
     "table": "ontime"
    }
   ]
  },
  {
   "title": "Carrier Destinations and Number of Flights",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "database": "airline",
     "dateColDataType": "FlightDate",
     "dateTimeColDataType": "toDateTime(FlightDate)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT Dest, count() Flights\n  FROM $table \n WHERE $timeFilter \n GROUP BY Dest ORDER BY Flights DESC",
     "round": "0s",
     "table": "ontime"
    }
   ]
  },
  {
   "title": "Total Carriers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT countDistinct(Carrier) FROM airline.ontime",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Number of Flights Operated by Carrier",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "airline",
     "dateColDataType": "FlightDate",
     "dateTimeColDataType": "toDateTime(FlightDate)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, count(*) Flights \n  FROM $table \n WHERE Carrier = '$carrier'\n   AND $timeFilter \n GROUP BY t ORDER BY t ",
     "round": "0s",
     "table": "ontime"
    }
   ]
  },
  {
   "title": "Percentage of Delayed Arrivals",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "airline",
     "dateColDataType": "FlightDate",
     "dateTimeColDataType": "toDateTime(FlightDate)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, sum(ArrDel15)/count(*)*100.0 as \"Carrier Average\"\n  FROM $table \n WHERE Carrier = '$carrier'\n   AND $timeFilter \n GROUP BY t ORDER BY t ",
     "round": "0s",
     "table": "ontime"
    },
    {
     "database": "airline",
     "dateColDataType": "FlightDate",
     "dateTimeColDataType": "toDateTime(FlightDate)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, sum(ArrDel15)/count(*)*100.0 as \"Industry Average\" \n  FROM $table \n WHERE $timeFilter \n GROUP BY t ORDER BY t ",
     "round": "0s",
     "table": "ontime"
    }
   ]
  },
  {
   "title": "Percentage of Cancelled Flights",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "airline",
     "dateColDataType": "FlightDate",
     "dateTimeColDataType": "toDateTime(FlightDate)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, sum(Cancelled)/count(*)*100.0 as \"Carrier Average\"\n  FROM $table \n WHERE Carrier = '$carrier'\n   AND $timeFilter \n GROUP BY t ORDER BY t ",
     "round": "0s",
     "table": "ontime"
    },
    {
     "database": "airline",
     "dateColDataType": "FlightDate",
     "dateTimeColDataType": "toDateTime(FlightDate)",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, sum(Cancelled)/count(*)*100.0 as \"Industry Average\" \n  FROM $table \n WHERE $timeFilter \n GROUP BY t ORDER BY t ",
     "round": "0s",
     "table": "ontime"
    }
   ]
  }
 ]
}