# ClickHouse using EBS gp3 storage on m6i.4xlarge VM. 
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "demo"
spec:
  configuration:
    clusters:
      - name: "ebs"
        layout:
          replicas:
          - templates:
              podTemplate: replica-1
          shardsCount: 1
        templates:
          volumeClaimTemplate: storage
  templates:
    podTemplates:
      - name: replica-1
        spec:
          containers:
          - name: clickhouse
            image: altinity/clickhouse-server:22.8.15.25.altinitystable
          nodeSelector:
            node.kubernetes.io/instance-type: m6i.large
    volumeClaimTemplates:
      - name: storage
        # reclaimPolicy: Retain
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Gi
