# ClickHouse using default storage class. 
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "aws2"
spec:
  configuration:
    clusters:
      - name: "cl"
        layout:
          replicas:
          - templates:
              podTemplate: clickhouse-zone-2a
          - templates:
              podTemplate: clickhouse-zone-2b
          shardsCount: 1
        templates:
          volumeClaimTemplate: storage
    zookeeper:
        nodes:
        - host: zookeeper.zoo1ns
          port: 2181
  templates:
    podTemplates:
      - name: clickhouse-zone-2a
        podDistribution:
          - type: ClickHouseAntiAffinity
            scope: ClickHouseInstallation
        spec:
          containers:
          - name: clickhouse
            image: altinity/clickhouse-server:23.3.8.22.altinitystable
          nodeSelector: 
            node.kubernetes.io/instance-type: m6i.large
        zone:
          key: topology.kubernetes.io/zone
          values:
          - us-west-2a
      - name: clickhouse-zone-2b
        podDistribution:
          - type: ClickHouseAntiAffinity
            scope: ClickHouseInstallation
        spec:
          containers:
          - name: clickhouse
            image: altinity/clickhouse-server:23.3.8.22.altinitystable
          nodeSelector: 
            node.kubernetes.io/instance-type: m6i.large
        zone:
          key: topology.kubernetes.io/zone
          values:
          - us-west-2b

    volumeClaimTemplates:
      - name: storage
        reclaimPolicy: Retain
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
