{
 "title": "Host Performance",
 "description": "Performance data from vmstat",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host Name",
    "query": "SELECT DISTINCT host\nFROM monitoring.vmstat"
   }
  ]
 },
 "panels": [
  {
   "title": "Average CPU usage by host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "monitoring",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t, \n    host, \n    100 - avg(id) as cpu_usage \nFROM monitoring.vmstat\nWHERE $timeFilter\nGROUP BY t, host\nORDER BY host,t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t, \n    host, \n    100 - avg(id) as cpu_usage \nFROM monitoring.vmstat\nWHERE timestamp >= toDateTime(1674514272) AND timestamp <= toDateTime(1674515172)\nGROUP BY t, host\nORDER BY host,t",
     "round": "0s",
     "table": "vmstat"
    }
   ]
  },
  {
   "title": "CPU Usage: ${host}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "database": "monitoring",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(us) AS user,\n    avg(sy) AS system,\n    avg(st) AS steal,\n    avg(wa) AS io_wait,\n    avg(id) AS idle\nFROM monitoring.vmstat\nWHERE $timeFilter\nAND length([${host}]) = 1\nAND host IN (${host})  \nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t,\n    avg(us) AS user,\n    avg(sy) AS system,\n    avg(st) AS steal,\n    avg(wa) AS io_wait,\n    avg(id) AS idle\nFROM monitoring.vmstat\nWHERE timestamp >= toDateTime(1674515078) AND timestamp <= toDateTime(1674515978)\nAND length(['logos3']) = 1\nAND host IN ('logos3')  \nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "vmstat"
    }
   ]
  },
  {
   "title": "Memory Usage: ${host}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "database": "monitoring",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    avg(swpd) AS swap,\n    avg(buff) AS buff,\n    avg(cache) AS cache,\n    avg(free) AS free\nFROM monitoring.vmstat\nWHERE $timeFilter\nAND length([${host}]) = 1\nAND host IN (${host})  \nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t,\n    avg(swpd) AS swap,\n    avg(buff) AS buff,\n    avg(cache) AS cache,\n    avg(free) AS free\nFROM monitoring.vmstat\nWHERE timestamp >= toDateTime(1674515078) AND timestamp <= toDateTime(1674515978)\nAND length(['logos2']) = 1\nAND host IN ('logos2')  \nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "vmstat"
    }
   ]
  }
 ]
}