# ClickHouse using default storage class. 
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "{{ .Values.clickhouse.name }}"
  labels:
    application_group: "{{ .Values.all.metadata.labels.application_group }}"
spec:
  configuration:
    clusters:
      - name: "{{ .Values.clickhouse.cluster }}"
        layout:
          shards:
            - replicas:
                {{- range .Values.clickhouse.zones }}
                - templates:
                    podTemplate: replica-in-zone-{{ . }}
                {{- end }}
        templates:
          podTemplate: replica
    zookeeper:
        nodes:
        - host: "{{ .Values.keeper.name }}"
          port: 2181
  templates:
    podTemplates:
      {{- range .Values.clickhouse.zones }}
      - name: replica-in-zone-{{ . }}
        zone:
          values:
            - {{ . }}
        podDistribution:
          - type: ClickHouseAntiAffinity
            scope: ClickHouseInstallation
        spec:
          containers:
          - name: clickhouse
            image: {{ $.Values.clickhouse.image }}
          nodeSelector:
            node.kubernetes.io/instance-type: {{ $.Values.clickhouse.nodeSelector }}
      {{- end }}
    volumeClaimTemplates:
      - name: storage
        reclaimPolicy: Retain
        metadata:
          labels:
            application_group: "{{ .Values.all.metadata.labels.application_group }}"
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "{{ .Values.clickhouse.storage }}"
